MODULES=(overlay vfat)
HOOKS=(base systemd autodetect microcode modconf kms plymouth memdisk overlay loop keyboard sd-vconsole block filesystems)
COMPRESSION="zstd"
COMPRESSION_OPTIONS=(--ultra --fast=22 -T0 --auto-threads=physical)
MODULE_DECOMPRESS="no"
