d /var/user/malwareslayer/cache 0755 malwareslayer malwareslayer -
d /var/user/malwareslayer/conda 0755 malwareslayer malwareslayer -
d /var/user/malwareslayer/containers 0755 malwareslayer malwareslayer -
d /var/user/malwareslayer/gradle 0755 malwareslayer malwareslayer -
d /var/user/malwareslayer/pipx 0755 malwareslayer malwareslayer -
d /var/user/malwareslayer/podman 0755 malwareslayer malwareslayer -
d /var/user/malwareslayer/steam 0755 malwareslayer malwareslayer -
d /var/user/malwareslayer/vulkan 0755 malwareslayer malwareslayer -
