d /var/user/malwareslayer/conda 0755 malwareslayer malwareslayer -
d /var/user/malwareslayer/containers 0755 malwareslayer malwareslayer -
d /var/user/malwareslayer/gradle 0755 malwareslayer malwareslayer -
d /var/user/malwareslayer/pipx 0755 malwareslayer malwareslayer -
d /var/user/malwareslayer/steamapps 0755 malwareslayer malwareslayer -
