d /dev/shm/AMD 0755 malwareslayer malwareslayer -
d /dev/shm/fontconfig 0755 malwareslayer malwareslayer -
d /dev/shm/mesa_shader_cache 0755 malwareslayer malwareslayer -
d /dev/shm/mesa_shader_cache_db 0755 malwareslayer malwareslayer -
d /dev/shm/radv_builtin_shaders 0755 malwareslayer malwareslayer -
d /dev/shm/shadercache 0755 malwareslayer malwareslayer -

