# Configuration file for NetworkManager.
# See "man 5 NetworkManager.conf" for details.

[main]
dhcp=dhclient
dns=none
firewall-backend=nftables
rc-manager=unmanaged

[connection]
connection.dns-over-tls=yes
connection.llmnr=no
connection.mdns=yes

wifi.cloned-mac-address=stable

ipv4.dhcp-ipv6-only-preferred=true
ipv4.dhcp-send-release=true

ipv4.route-metric=true

ipv6.method=auto
ipv6.never-default=false

ipv6.dhcp-duid=stable-uuid
ipv6.dhcp-send-release=true

ipv6.route-metric=true

[device]
wifi.backend=iwd
wifi.iwd.autoconnect=true
