#     path                                          mode user  group age options
d     /dev/shm/AMD                 		    0755 60466 60466 -
d     /dev/shm/fontconfig		 	    0755 60466 60466 -
d     /dev/shm/gtk-4.0				    0755 60466 60466 -
d     /dev/shm/mesa_shader_cache                    0755 60466 60466 -
d     /dev/shm/mesa_shader_cache_db                 0755 60466 60466 -
d     /dev/shm/radv_builtin_shaders                 0755 60466 60466 -
d     /dev/shm/shadercache                 	    0755 60466 60466 -

